config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'home#index', as: :root

  namespace :admins do
    resource :config do
    end
  end

  namespace :users do
    resource :my_page
  end

  resource :home, controller: 'home' do
    get 'contact'
    get 'news'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/transaction_history.rb
class TransactionHistory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/admins/base_controller.rb
module Admins
  class BaseController
    before_action :authenticate_user!
  end
end

app/controllers/admins/config_controller.rb
module Admins
  class ConfigController < Admins::BaseController
    before_action :sign_in_required
    
    def index
    end

    def new
    end

    def create
    end

    def destroy
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    my_page_path
  end

  private
  def sign_in_required
    redirect_to new_user_session_url unless user_signed_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'public'

  def index
    @news = News.all
  end

  def contact
  end

  def news
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController  < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/base_controller.rb
module Users
  class BaseController < ApplicationController
    before_action :authenticate_user!
  end
end

app/controllers/users/my_page_controller.rb
module Users
  class MyPageController < Users::BaseController
    before_action :sign_in_required
    
    def index
    end

    def new
    end

    def create
    end

    def destroy
    end
  end
end

app/helpers/admins/config_helper.rb
module Admins::ConfigHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/users/my_page_helper.rb
module Users::MyPageHelper
end

app/views/admins/config/create.html.erb
<h1>Admins::Config#create</h1>
<p>Find me in app/views/admins/config/create.html.erb</p>

app/views/admins/config/destroy.html.erb
<h1>Admins::Config#destroy</h1>
<p>Find me in app/views/admins/config/destroy.html.erb</p>

app/views/admins/config/index.html.erb
<h1>Admins::Config#index</h1>
<p>Find me in app/views/admins/config/index.html.erb</p>

app/views/admins/config/new.html.erb
<h1>Admins::Config#new</h1>
<p>Find me in app/views/admins/config/new.html.erb</p>

app/views/home/index.html.erb
<section class="preview-welcome-area text-center" id="home">
  <div class="table">
    <div class="table_cell">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <div class="preview_text_area">
              <h2><%= t('home.title') %></h2>
              <p><%= t('home.explanation') %></p>
              <a href="#" class="btn btn-lg preview-btn"><%= t('home.need_info') %></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="content_area section_padding_100_50">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="section_heading">
          <h2><%= t('home.menu') %></h2>
          <p><%= t('home.menu_comment') %></p>
        </div>
      </div>
    </div>
    <div class="row">
      <% @news.each do |news|%>
      <div class="col-12 col-md-6 col-lg-4 wow fadeInUpBig" data-wow-delay="0.1s" data-wow-duration="1s" style="visibility: visible; animation-duration: 1s; animation-delay: 0.1s; animation-name: fadeInUpBig;">
        <div class="single_page_content">
          <%= link_to(content_tag(:img, src: '/images/default.png'), news_home_path(news.id))  %>
        </div>
        <div class="title">
          <h3><%= news.title %></h3>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/home/partial/_footer.html.erb
<footer class="footer_area">
  <div class="footer_copywrite_area">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <!-- Footer Copwrite Area -->
          <div class="footer_bottom text-center">
            <p>© 2017
              <a href="#">Asahi town</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/home/partial/_header.html.erb
<div class="header" data-view="ctaHeader">

  <div class="logo">
    <%= link_to t('name'), home_path %>
  </div>

  <div class="action">
    <div class="login-area">
      <%= link_to t('login'), new_user_session_path, { class: "login-btn color-primary" } %>
    </div>
    <div class="logout-area">
      <a href="<%= destroy_user_session_path %>">
        <i class="e-icon -icon-cancel"></i>
        <span><%= t('logout') %></span>
      </a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsahiTown</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer>
      <p>© 2017 Asahi town</p>
    </footer>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsahiTown</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if notice.present? %>
    <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
    <p class="alert"><%= alert %></p>
    <% end %>
    <%= render partial: 'home/partial/header' %>
    <%= yield %>
    <%= render partial: 'home/partial/footer' %>
  </body>
</html>

app/views/users/my_page/create.html.erb
<h1>Users::MyPage#create</h1>
<p>Find me in app/views/users/my_page/create.html.erb</p>

app/views/users/my_page/destroy.html.erb
<h1>Users::MyPage#destroy</h1>
<p>Find me in app/views/users/my_page/destroy.html.erb</p>

app/views/users/my_page/index.html.erb
<h1>Users::MyPage#index</h1>
<p>Find me in app/views/users/my_page/index.html.erb</p>

app/views/users/my_page/new.html.erb
<h1>Users::MyPage#new</h1>
<p>Find me in app/views/users/my_page/new.html.erb</p>